### ISSUE TITLE
引战？

### ISSUE THREAD

**Issue by tong-ge** [JieningYu/Extreme-Forge-Fanbois#2]
这个仓库看着就很引战，试图挑动Forge与Fabric的对立
还有，攻击xmzh服务器的真的不是我
我最后一次启动压测是在11月5日，目标ip 127.0.0.1
![image](https://user-images.githubusercontent.com/40582371/201505011-10a1d051-e7e9-4c34-9e92-db3a52a8308e.png)

**Comment by JieningYu** [comment]
这个仓库里存的都一堆弱智图片
如果您真的没攻击xmzh服务器，那我给您道个歉

**Comment by JieningYu** [comment]
若果你想的话请证明你没有攻击xmzh的服务器。

**Comment by tong-ge** [comment]
证有不证无，谁主张谁举证。
请证明攻击xmzh的人是我
但还是附上一张截图
<img width="845" alt="屏幕截图 2022-11-17 212009" src="https://user-images.githubusercontent.com/40582371/202457565-142d9893-8052-4ff9-9b0c-701a6f8c8194.png">

**Comment by JieningYu** [comment]
你上次开压测是11/5并不能说明你之前没开过xmzh的。
另外你可以修改日期

**Comment by tong-ge** [comment]
据我所知xmzh受攻击至少是11/9之后的事了

**Comment by JieningYu** [comment]
你可以修改日期，并且据我所知xmzh受攻击远在11/9前。

**Comment by tong-ge** [comment]
你要我提供什么？我尽可能给你提供

**Comment by JieningYu** [comment]
既然你无法证明，那我只能认为是你攻击的了。

**Comment by tong-ge** [comment]
但是你有证据证明是我攻击的吗？

**Comment by JieningYu** [comment]
你有证据证明你没有吗？

**Comment by tong-ge** [comment]
证有不证无，你一开始就应该把我攻击你的证据贴出来

**Comment by JieningYu** [comment]
这你要问@xmzh0603
